version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: food_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: food_delivery
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
    container_name: food_backend
    environment:
      DB_URL: jdbc:mysql://mysql:3306/food_delivery?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: password
      JAVA_OPTS: -Xms256m -Xmx512m
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080/api
    container_name: food_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:

